### ISSUE TITLE
Volume empty ?

### ISSUE THREAD

**Issue by ManuCloudd** [C4illin/ConvertX#116]
hello,
Installed the main version
I customized the path via a volume.

Maybe I was wrong, but the data in the volume is not replicated. :(

copy the conf (be careful I'm new to docker :) )

in the container

![image](https://github.com/user-attachments/assets/def442c7-ba2d-4319-914b-695dafbb7a7d)

in the host 'the volume is empty :'(

![image](https://github.com/user-attachments/assets/0b332553-cf12-4430-b060-759df455e2de)

&

![image](https://github.com/user-attachments/assets/6acf7d47-601b-41c0-b171-39ab8ba602c4)

In any case, congratulations for your project and its incredible usefulness. I think that in the long term it will become a must have for anyone looking for self-hosting ^^ . Having such an open source and practical tool will become essential for many.

I am following the project :)

**Comment by C4illin** [comment]
What does your compose file look like?

**Comment by ManuCloudd** [comment]
> What does your compose file look like?
Hello
This
![image](https://github.com/user-attachments/assets/d123df68-dec5-425b-907f-c975d266bada)

**Comment by C4illin** [comment]
Test without PGID and PUID

**Comment by luis-c465** [comment]
> > What does your compose file look like?
> > Hello
> > This
> > ![image](https://private-user-images.githubusercontent.com/119607747/359570666-d123df68-dec5-425b-907f-c975d266bada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODYxMDEsIm5iZiI6MTcyNDE4NTgwMSwicGF0aCI6Ii8xMTk2MDc3NDcvMzU5NTcwNjY2LWQxMjNkZjY4LWRlYzUtNDI1Yi05MDdmLWM5NzVkMjY2YmFkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQyMDMwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTAxZjcxMDMzZGU3OTQzOGI0ZWQ5ZWZjZjMzODY4M2NmNWI2NWI4MmNkMTJkMWE1Njk0YmJjZDlhNTdiYTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwx7xUS_XguyiP9Y_CeEFF9Gp-7S418EQwjoa9GFWVE)

Looking at the docker compose file, it looks like you put the volume mount point wrong :)

It should be `/app/data` and not `/data`

So the final docker compose file would be the following:

```yml
version: "3"
# docker-compose.yml
services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped # <- You may also want this, makes the container restart if it crashes
    ports:
      - "34444:3000"
    environment: # Defaults are listed below. All are optional.
      #- ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() by default
      - HTTP_ALLOWED=true # setting this to true is unsafe, only set this to true locally
    volumes:
      - convertx_data:/app/data # <- The volume mount point

volumes:
  convertx_data:
```

Let me know if this compose file works!
