### ISSUE TITLE
page went blank after login

### ISSUE THREAD

**Issue by feickoo** [C4illin/ConvertX#139]
Here is my compose file
```yaml
services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
    environment:
      - ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - JWT_SECRET=aLongAndSecretStringUsedTebToken123uygh4 # will use randomUUID() by default
      - HTTP_ALLOWED=true# setting this to true is unsafe, only set this to true
        locally
      - ALLOW_UNAUTHENTICATED=true # allows anyone to use the service without logging in, only set this to true locally
      - AUTO_DELETE_EVERY_N_HOURS=0 # checks every n hours for files older then n hours and deletes them, set to 0 to disable
    volumes:
      - /appdata/convertx:/app/data
networks: {}
```

I registered the account and tried to login. I will always get blank page error 500. It never works for me. Is it a bug?
