### ISSUE TITLE
Still required to register for new account despite `ACCOUNT_REGISTRATION=false` and `ALLOW_UNAUTHENTICATED=true`

### ISSUE THREAD

**Issue by tejashah88** [C4illin/ConvertX#201]
I have the following docker-compose.yml file to launch this app locally on my PC for personal use.

```yaml
services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - ACCOUNT_REGISTRATION=false
      - ALLOW_UNAUTHENTICATED=true
      - AUTO_DELETE_EVERY_N_HOURS=0
      - HTTP_ALLOWED=true
    volumes:
      - ./data:/app/data
```

I tried running this with Docker Compose but when opening up the webpage on `localhost:3000`, it leads me to a setup page, where I'm required to register for an account despite specifying `ACCOUNT_REGISTRATION=false` and `ALLOW_UNAUTHENTICATED=true` and `HTTP_ALLOWED=true`. This was tested on an Incognito Window using the Brave Browser (Chrome-based) on a Windows 10 Pro Laptop.

![image](https://github.com/user-attachments/assets/6aada905-239c-4541-bbe8-276c9236aed6)

Peering through the source code, I think I found a potential culprit. The [`FIRST_RUN` variable is set](https://github.com/C4illin/ConvertX/blob/cf2b026dc47a0215493e169c6f0985ded771e034/src/index.tsx#L85) when no users exist, but the `ALLOW_UNAUTHENTICATED` flag [is not checked](https://github.com/C4illin/ConvertX/blob/cf2b026dc47a0215493e169c6f0985ded771e034/src/index.tsx#L460) in conjunction,  which causes the routing to send the user to `/setup` until a user is finally found in the database.

I can imagine a temporary workaround is to put a dummy user into the database when `ALLOW_UNAUTHENTICATED` is set to true, but I'd like to know what you think.
