### ISSUE TITLE
"Job not found" message when attempting to convert files

### ISSUE THREAD

**Issue by bradkeller** [C4illin/ConvertX#23]
I receive the following error when trying to convert files using the v0.1.1 release of your application:
```
{
    "message": "Job not found."
}
```
Configuration is as follows:
```
services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    ports:
      - "3002:3000"
    environment: # Defaults are listed below. All are optional.
      - ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() by default
      - HTTP_ALLOWED=true # setting this to true is unsafe, only set this to true locally
    volumes:
      - /home/brakelle/config/convertx:/app/data
```
