### ISSUE TITLE
How to enable PanDoc PDF operations?

### ISSUE THREAD

**Issue by smileBeda** [C4illin/ConvertX#231]
I thought Pandoc would be enabled for PDF too but maybe I am wrong.
I tried to add a PDF file and convert it using pandoc but the options are not available. Only `vips, calibre, graphicsmagick, Inkscape` appear when I upload a PDF.

Docker file:
```
services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3007:3000"
    environment:
      - JWT_SECRET=EDITED
      - HTTP_ALLOWED=true
    volumes:
      - ./data:/app/data
    networks:
      proxy:
        ipv4_address: 192.168.100.35

networks:
  proxy:
    external: true
    name: npm_proxy
```

Pandoc does support PDF, but it needs additional libs I believe...

PS:
for example `md` files allow Pandoc just fine, so I guess it is related to these additional libs required?
