### ISSUE TITLE
With Docker : Error Unexpected reading "/app/src/index.tsx"

### ISSUE THREAD

**Issue by xavier-GitHub76** [C4illin/ConvertX#235]
Hello,

I use Convertx with Docker container.

I have the error : "Unexpected reading "/app/src/index.tsx"
I clean my install, I download the latest image 

![Image](https://github.com/user-attachments/assets/648f81be-f0d8-472e-93fc-fa2c7e1d7eaf)

and I build my docker compose but the error is always present

![Image](https://github.com/user-attachments/assets/8fc1cba0-4613-4c00-8a4e-877d22629320)

Regards

**Comment by xavier-GitHub76** [comment]
networks:
...

services:
  # L'application
  convertx:
    image: ${IMAGE}:${VERSION:-latest}
    container_name: convertx
    networks:
      - convertx-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    security_opt:
      - no-new-privileges
    ports:
      - "17659:3000"
    volumes:
      - ./data:/app/data:rw
    environment:
      - ACCOUNT_REGISTRATION=${ACCOUNT_REGISTRATION}
      - JWT_SECRET=${JWT_SECRET}
      - HTTP_ALLOWED=${HTTP_ALLOWED}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

**Comment by MuadDibVV** [comment]
I have the same error on v0.12.0
No problem with v0.11.1

**Comment by C4illin** [comment]
Weird that so many get it now, I am not able to reproduce it unfortunately

**Comment by C4illin** [comment]
Could you maybe test the `:main` image? Doubt that it will help, but maybe something is currupt in the release?

**Comment by monesje** [comment]
I've got the same issue on upgrading to v0.12.0. Running out of Container Manager on a Synology DS-423+ 
No issues once I reverted back to v0.11.1. 


My compose was:

```
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - 3005:3000
    environment:
      - JWT_SECRET=gYy4aXF2Ppwm2qGfz9izJeWUVepeLxvt # will use randomUUID() if unset
      - PUID=1039
      - PGID=100
      - ACCOUNT_REGISTRATION=false
      - HTTP_ALLOWED=true
      - ALLOW_UNAUTHENTICATED=true
      - AUTO_DELETE_EVERY_N_HOURS=24
    volumes:
      - ./convertx:/app/data
    networks:
      - tunneling
    depends_on:
      - nginx
```
