### ISSUE TITLE
Latest release breaks v0.14.1

### ISSUE THREAD

**Issue by begunfx** [C4illin/ConvertX#314]
**Describe the bug**
Installing via docker compose.  Happens when building the container

Docker compose file:
```
services:
  convertx: 
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 3522:3000
    environment:
      JWT_SECRET: XXX
      ACCOUNT_REGISTRATION: false #Set To false To Disallow User Registration.
      HTTP_ALLOWED: true #Allow HTTP Connections, Only Set This To true Locally.
      ALLOW_UNAUTHENTICATED: false 	#Allow Unauthenticated Users To Use The Service, Only Set This To true Locally.
      AUTO_DELETE_EVERY_N_HOURS: 24
      TZ: America/Los_Angeles
    volumes:
      - /volume1/docker/convertx:/app/data:rw
    restart: unless-stopped
```

Here's the error log:
```
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
jobId set to: 33
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
jobId set to: 34
ConvertX v0.14.0
🦊 Elysia is running at http://localhost:3000
Debian GNU/Linux 13 (trixie)
resvg v0.45.1
Bun v1.2.2
potrace 1.16. Copyright (C) 2001-2019 Peter Selinger.
assimp Version 5.4 -debug -shared -st (GIT commit 0)
libheif v1.19.8
ImageMagick 7.1.1-43 Q16 x86_64 22550 https://imagemagick.org
XeTeX 3.141592653-2.6-0.999996 (TeX Live 2025/dev/Debian)
djxl v0.11.1 [AVX2,SSE4,SSE2]
GraphicsMagick 1.4 snapshot-20250331 Q16 http://www.GraphicsMagick.org/
pandoc 3.1.11.1
vips-8.16.1
ebook-convert (calibre 8.4.0)
ffmpeg version 7.1.1-1+b1 Copyright (c) 2000-2025 the FFmpeg developers
Inkscape 1.4 (e7c3feb100, 2024-10-09)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
error: NOT_FOUND
 status: 404,
   code: "NOT_FOUND"
      at NotFoundError (/app/node_modules/elysia/src/error.ts:87:3)
```
